### PR TITLE
#166840909 Add heroku configuration files

### PR DESCRIPTION
**Pull request by timi-codes**
#### What does this PR do?
- This PR adds Heroku Procfile 
-  This PR adds app.json file for Heroku app review

#### Description of Task to be completed?
Procfile  - I set up a simple command `web:npm start`  which is called at app startup

#### How should this be manually tested?
N/A
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166840909](https://www.pivotaltracker.com/story/show/166840909)
#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

image

### CODE REVIEW

**Comment by timi-codes** [comment]
Okay, @codexempire. Thanks for the observation.

**Comment by olorunwalawrence** [comment]
I observe you have a build before deployment. that was awesome. good job.

**Comment by tolumide-ng** [comment]
Well done 👍, looks good to me

**Comment by Onyimatics** [comment]
Successful builds! Now we have builds, well-done teammates!

**Comment by codexempire** [comment]
Great work @timi-codes glad for the staging builds 👏

**Review by tolumide-ng — APPROVED** [review]

**Pull request merged**
