### PR TITLE
ch(setup sequelize):postgres setup

### PR DESCRIPTION
**Pull request by olorunwalawrence**
#### What does this PR do?
- setup authors haven to use Sequelize as an ORM.

#### Description of Task to be completed?
- install sequelize
- install sequelize-cli
- install pg
- install pg-hstore

#### How should this be manually tested?
- clone the [repo ]https://github.com/andela/ah-kifaru-backend)
- on your terminal, run `git checkout  ch-setup-sequelize-166840906`
- on your terminal, run npm install to install dependencies
- on your terminal, run npm run start:dev to start the application.
    
####  What are the relevant pivotal tracker stories?
[#166840906](https://www.pivotaltracker.com/story/show/166840906)

### CODE REVIEW

**Comment by Onyimatics** [comment]
Good work! However, please try and see if you can gitignore the .env file. I can see it's in the branch you pushed. Thank you.

**Comment by tohbay** [comment]
Nice work Lawrence.
Just as Onyinye pointed out, it will be nice to remove the `.env` file from the codebase for security reasons.

**Comment by tobechukwuobitube** [comment]
Nice work Lawrence.
Just as Onyinye pointed out, it will be nice to remove the `.env` file from the codebase for security reasons.

**Comment by timi-codes** [comment]
Nice work @olorunwalawrence. You did a great job by removing .env file as noted by the team.

**Pull request merged**
