### PR TITLE
166840913 setup API documentation using swagger

### PR DESCRIPTION
**Pull request by Onyimatics**
### What does this PR do?
- setup API documentation using swagger

#### Description of Task to be completed?
- setup API documentation using swagger

#### How should this be manually tested?
- clone the repo
- run npm install
- start server at port 3000
- open browser and hit http://localhost:3000/docs/

#### Any background context you want to provide?
- N/A

#### What are the relevant pivotal tracker stories?
- [#166840913](https://www.pivotaltracker.com/story/show/166840913)

#### Screenshots (if appropriate)
Screenshot 2019-06-25 at 12 21 43 PM

#### Questions:
- N/A

### CODE REVIEW

**Comment by tolumide-ng** [comment]
Hello @Onyimatics , thank you for removing package-lock.json file as we discussed. I have reviewed the changes and it looks okay to me.

**Comment by kechyy** [comment]
Looks Okay to me. I like the fact that you made it simple and it also followed normal convention.
Well done Onyinye.

**Comment by segunolalive** [comment]
@Onyimatics, Kindly resolve the merge conflicts

**Comment by Onyimatics** [comment]
All right, I will do that. Thank you.

**Pull request merged**
