### PR TITLE
#166840907-chore(users): Installs eslint, houndCI and prettier

### PR DESCRIPTION
**Pull request by tolumide-ng**
#### What does this PR do?
Installs ESlint, Prettier, Husky, and activates HoundCI

#### Description of Task to be completed?
- Installs Eslint, adds .eslintrc and .eslintignore file with configuration
- Installs prettier for code formatting and adds .prettierrc and .prettierignore 
- Adds .hound.yml configuration

#### How should this be manually tested?
Clone the repo, run npm install to install all dependencies, cd into the folder and run **npm run start:dev**

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
#166840907

### CODE REVIEW

**Comment by timi-codes** [comment]
Looks good to me.

**Comment by olorunwalawrence** [comment]
looks good.

**Comment by Onyimatics** [comment]
Looks good to me

**Comment by tohbay** [comment]
This looks good to me. 
However, I'd like to know why the linting files contain settings that are contrary to the basic linting rules specified by the Andela Engineering Playbook.

**Review by Duncan-Ireri — APPROVED** [review]
Looks good.

**Comment by tolumide-ng** [comment]
Hello @tobechukwuobitube , thank you for your question. The .eslintrc file contains the rules that were laid out on the pivotal tracker board ([please click here to view the board](https://www.pivotaltracker.com/n/projects/2355755)) and three lines tweaked to align with houndci.

**Pull request merged**
